package interfaz;

/**
 *
 * @author LENOVO
 */


public class calculadora extends javax.swing.JFrame {



    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Masculino = new javax.swing.JRadioButton();
        Femenino = new javax.swing.JRadioButton();
        titulo = new java.awt.Label();
        Tedad = new java.awt.Label();
        Testatura = new java.awt.Label();
        Tpeso = new java.awt.Label();
        icono = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        Peso = new javax.swing.JTextField();
        Estatura = new javax.swing.JTextField();
        Edad = new javax.swing.JTextField();

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 204, 204));
        setMinimumSize(new java.awt.Dimension(550, 450));
        getContentPane().setLayout(null);

        buttonGroup1.add(Masculino);
        Masculino.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Masculino.setText("Masculino");
        Masculino.setName("Masculino"); // NOI18N
        Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinoActionPerformed(evt);
            }
        });
        getContentPane().add(Masculino);
        Masculino.setBounds(40, 80, 150, 30);

        buttonGroup1.add(Femenino);
        Femenino.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Femenino.setText("Femenino");
        Femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemeninoActionPerformed(evt);
            }
        });
        getContentPane().add(Femenino);
        Femenino.setBounds(40, 110, 150, 30);

        titulo.setAlignment(java.awt.Label.CENTER);
        titulo.setBackground(new java.awt.Color(0, 143, 57));
        titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulo.setForeground(new java.awt.Color(250, 250, 250));
        titulo.setName(""); // NOI18N
        titulo.setText("Calculadora de IMC");
        getContentPane().add(titulo);
        titulo.setBounds(0, 0, 550, 50);

        Tedad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Tedad.setForeground(new java.awt.Color(0, 0, 0));
        Tedad.setName(""); // NOI18N
        Tedad.setText("Edad");
        getContentPane().add(Tedad);
        Tedad.setBounds(30, 160, 60, 20);

        Testatura.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Testatura.setForeground(new java.awt.Color(0, 0, 0));
        Testatura.setText("Estatura");
        getContentPane().add(Testatura);
        Testatura.setBounds(30, 190, 100, 28);

        Tpeso.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Tpeso.setForeground(new java.awt.Color(0, 0, 0));
        Tpeso.setText("Peso");
        getContentPane().add(Tpeso);
        Tpeso.setBounds(30, 230, 70, 28);

        icono.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfaz/h.png"))); // NOI18N
        icono.setToolTipText("");
        icono.setAlignmentY(0.0F);
        icono.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icono.setIconTextGap(10);
        icono.setMaximumSize(new java.awt.Dimension(100, 100));
        icono.setMinimumSize(new java.awt.Dimension(200, 200));
        icono.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(icono);
        icono.setBounds(220, 70, 360, 350);

        Calcular.setBackground(new java.awt.Color(0, 143, 57));
        Calcular.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Calcular.setForeground(new java.awt.Color(255, 255, 255));
        Calcular.setText("Calcular");
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Calcular);
        Calcular.setBounds(70, 320, 140, 40);

        Peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesoActionPerformed(evt);
            }
        });
        getContentPane().add(Peso);
        Peso.setBounds(170, 240, 60, 19);

        Estatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstaturaActionPerformed(evt);
            }
        });
        getContentPane().add(Estatura);
        Estatura.setBounds(170, 200, 60, 19);

        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });
        getContentPane().add(Edad);
        Edad.setBounds(170, 160, 60, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == Calcular) {

            setTitle(Peso.getText());

        }
    }//GEN-LAST:event_CalcularActionPerformed

    private void FemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemeninoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_FemeninoActionPerformed

    private void MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasculinoActionPerformed

    private void PesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesoActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_PesoActionPerformed



    private void EstaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstaturaActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField Edad;
    private javax.swing.JTextField Estatura;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JTextField Peso;
    private java.awt.Label Tedad;
    private java.awt.Label Testatura;
    private java.awt.Label Tpeso;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel icono;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private java.awt.Label titulo;

    // End of variables declaration//GEN-END:variables
}
