/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz;

/**
 *
 * @author LENOVO
 */
public class VentanaInfo extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public VentanaInfo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rutina = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dieta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 630));
        setSize(new java.awt.Dimension(500, 400));

        Imc.setBackground(new java.awt.Color(0, 77, 198));
        Imc.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Imc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Imc.setText("peso normal");
        Imc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImcActionPerformed(evt);
            }
        });

        Rutina.setColumns(20);
        Rutina.setRows(5);
        Rutina.setText("Rutina\n3–4 días de entrenamiento de fuerza (pesas, máquinas, calistenia).\nEjercicios compuestos: sentadillas, press banca, dominadas.\n15–20 min de cardio ligero 2 veces/semana (caminar rápido o bici suave).");
        jScrollPane1.setViewportView(Rutina);

        Dieta.setColumns(20);
        Dieta.setRows(5);
        Dieta.setText("Dieta sugerida:\nDesayuno: avena con leche + huevo + fruta (banano o mango).\nMedia mañana: yogurt griego + frutos secos.\nAlmuerzo: arroz + pollo o pescado + aguacate + ensalada.\nMerienda: batido de proteínas (leche + fruta + mantequilla de maní).\nCena: tortilla de huevo + queso + pan integral.\nRecomendación: excedente calórico ligero (+300-500 kcal/día).");
        jScrollPane2.setViewportView(Dieta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imc, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaInfo dialog = new VentanaInfo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setMensaje(String texto) {
        // Aquí uso HTML para que acepte saltos de línea
        Imc.setText(texto);
        Imc.setEditable(false);
    }

    public void setRutina(String texto) {
        // Aquí uso HTML para que acepte saltos de línea
        Rutina.setText(texto);
        Rutina.setEditable(false);
    }

    public void setDieta(String texto) {
        // Aquí uso HTML para que acepte saltos de línea
        Dieta.setText(texto);
        Dieta.setEditable(false);


    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Dieta;
    private javax.swing.JTextField Imc;
    private javax.swing.JTextArea Rutina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
